=== omg-dmn-taskforce/omg-dmn-spec/xsd/dmn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.omg.org/spec/DMN/20130901" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.omg.org/spec/DMN/20130901" elementFormDefault="qualified">
	<xsd:element name="DMNElement" type="tDMNElement" abstract="true"/>
	<xsd:complexType name="tDMNElement">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="optional"/>
		<xsd:anyAttribute namespace="##other" processContents="lax"/>
	</xsd:complexType>
	<xsd:element name="NamedElement" type="tNamedElement" substitutionGroup="DMNElement"/>
	<xsd:complexType name="tDMNElementReference">
		<xsd:attribute name="href" type="xsd:anyURI" use="required"/>
	</xsd:complexType>
	<xsd:element name="Definitions" type="tDefinitions" substitutionGroup="NamedElement"/>
	<xsd:complexType name="tDefinitions">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement">
				<xsd:sequence>
					<xsd:element ref="Import" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="ItemDefinition" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="DRGElement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="artifact" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="ElementCollection" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="BusinessContextElement" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:attribute name="expressionLanguage" type="xsd:anyURI" use="optional" default="http://www.omg.org/spec/FEEL/20140401"/>
				<xsd:attribute name="typeLanguage" type="xsd:anyURI" use="optional" default="http://www.omg.org/spec/FEEL/20140401"/>
				<xsd:attribute name="namespace" type="xsd:anyURI" use="required"/>
				<xsd:attribute name="exporter" type="xsd:string" use="optional"/>
				<xsd:attribute name="exporterVersion" type="xsd:string" use="optional"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="Import" type="tImport"/>
	<xsd:complexType name="tImport">
		<xsd:attribute name="namespace" type="xsd:anyURI" use="required"/>
		<xsd:attribute name="locationURI" type="xsd:anyURI" use="optional"/>
		<xsd:attribute name="importType" type="xsd:anyURI" use="required"/>
	</xsd:complexType>
	<xsd:element name="ElementCollection" type="tElementCollection" substitutionGroup="NamedElement"/>
	<xsd:complexType name="tElementCollection">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement">
				<xsd:sequence>
					<xsd:element name="drgElement" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="DRGElement" type="tDRGElement" abstract="true" substitutionGroup="NamedElement"/>
	<xsd:complexType name="tDRGElement">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="Decision" type="tDecision" substitutionGroup="DRGElement"/>
	<xsd:complexType name="tDecision">
		<xsd:complexContent>
			<xsd:extension base="tDRGElement">
				<xsd:sequence>
					<xsd:element name="question" type="xsd:string" minOccurs="0" maxOccurs="1"/>
					<xsd:element name="allowedAnswers" type="xsd:string" minOccurs="0" maxOccurs="1"/>
					<xsd:element ref="InformationItem" minOccurs="0"/>
					<xsd:element name="informationRequirement" type="tInformationRequirement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="knowledgeRequirement" type="tKnowledgeRequirement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="authorityRequirement" type="tAuthorityRequirement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="supportedObjective" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="impactedPerformanceIndicator" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="decisionMaker" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="decisionOwner" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="usingProcess" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="usingTask" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="Expression" minOccurs="0" maxOccurs="1"/>
					<!-- the decision logic -->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="BusinessContextElement" type="tBusinessContextElement" abstract="true"/>
	<xsd:complexType name="tBusinessContextElement">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement">
				<xsd:attribute name="URI" type="xsd:anyURI" use="optional"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="PerformanceIndicator" type="tPerformanceIndicator" substitutionGroup="BusinessContextElement"/>
	<xsd:complexType name="tPerformanceIndicator">
		<xsd:complexContent>
			<xsd:extension base="tBusinessContextElement">
				<xsd:sequence>
					<xsd:element name="impactingDecision" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="OrganizationUnit" type="tOrganizationUnit" substitutionGroup="BusinessContextElement"/>
	<xsd:complexType name="tOrganizationUnit">
		<xsd:complexContent>
			<xsd:extension base="tBusinessContextElement">
				<xsd:sequence>
					<xsd:element name="decisionMade" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="decisionOwned" type="tDMNElementReference" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="BusinessKnowledgeModel" type="tBusinessKnowledgeModel" substitutionGroup="DRGElement"/>
	<xsd:complexType name="tBusinessKnowledgeModel">
		<xsd:complexContent>
			<xsd:extension base="tDRGElement">
				<xsd:sequence>
					<!-- the parameters -->
					<xsd:element ref="FunctionDefinition" minOccurs="0" maxOccurs="1"/>
					<!-- the body -->
					<xsd:element name="knowledgeRequirement" type="tKnowledgeRequirement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="authorityRequirement" type="tAuthorityRequirement" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="InputData" type="tInputData" substitutionGroup="DRGElement"/>
	<xsd:complexType name="tInputData">
		<xsd:complexContent>
			<xsd:extension base="tDRGElement">
				<xsd:sequence>
					<xsd:element ref="InformationItem" minOccurs="0"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="KnowledgeSource" type="tKnowledgeSource" substitutionGroup="DRGElement"/>
	<xsd:complexType name="tKnowledgeSource">
		<xsd:complexContent>
			<xsd:extension base="tDRGElement">
				<xsd:sequence>
					<xsd:element name="authorityRequirement" type="tAuthorityRequirement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="type" type="xsd:anyType" minOccurs="0" maxOccurs="1"/>
					<xsd:element name="owner" type="tDMNElementReference" minOccurs="0" maxOccurs="1"/>
				</xsd:sequence>
				<xsd:attribute name="locationURI" type="xsd:anyURI" use="optional"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="tInformationRequirement">
		<xsd:sequence>
			<!-- the variable -->
			<xsd:choice minOccurs="1" maxOccurs="1">
				<xsd:element name="requiredDecision" type="tDMNElementReference"/>
				<xsd:element name="requiredInput" type="tDMNElementReference"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="tKnowledgeRequirement">
		<xsd:sequence>
			<xsd:element name="requiredKnowledge" type="tDMNElementReference" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="tAuthorityRequirement">
		<xsd:choice minOccurs="1" maxOccurs="1">
			<xsd:element name="requiredDecision" type="tDMNElementReference"/>
			<xsd:element name="requiredInput" type="tDMNElementReference"/>
			<xsd:element name="requiredAuthority" type="tDMNElementReference"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:element name="Expression" type="tExpression" abstract="true"/>
	<xsd:complexType name="tExpression">
		<xsd:complexContent>
			<xsd:extension base="tDMNElement"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="ItemDefinition" type="tItemDefinition" substitutionGroup="NamedElement"/>
	<xsd:complexType name="tItemDefinition">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement">
				<xsd:choice>
					<xsd:sequence>
						<xsd:element name="typeRef" type="xsd:QName"/>
						<xsd:element name="allowedValues" type="tUnaryTests" minOccurs="0"/>
					</xsd:sequence>
					<xsd:element name="itemComponent" type="tItemDefinition" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:choice>
				<xsd:attribute name="typeLanguage" type="xsd:anyURI" use="optional"/>
				<xsd:attribute name="isCollection" type="xsd:boolean" use="optional" default="false"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="LiteralExpression" type="tLiteralExpression" substitutionGroup="Expression"/>
	<xsd:complexType name="tLiteralExpression">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:choice minOccurs="0" maxOccurs="1">
					<xsd:element name="text" type="xsd:string"/>
					<xsd:element ref="importedValues"/>
				</xsd:choice>
				<xsd:attribute name="expressionLanguage" type="xsd:anyURI" use="optional"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="Invocation" type="tInvocation" substitutionGroup="Expression"/>
	<xsd:complexType name="tInvocation">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:sequence>
					<xsd:element name="binding" type="tBinding" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="tBinding">
		<xsd:sequence>
			<xsd:element ref="Expression" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="parameter" type="tDMNElementReference" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="InformationItem" type="tInformationItem" substitutionGroup="NamedElement"/>
	<xsd:complexType name="tInformationItem">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement">
				<xsd:sequence>
					<xsd:element name="itemDefinition" type="xsd:QName" minOccurs="0" maxOccurs="1"/>
				</xsd:sequence>
			</xsd:extension>
			<!-- NB: the name attribute is "required" for information items -->
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="DecisionTable" type="tDecisionTable" substitutionGroup="Expression"/>
	<xsd:complexType name="tDecisionTable">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:sequence>
					<xsd:element name="input" type="tDTInput" minOccurs="0" maxOccurs="unbounded"/>
					<!-- NB: when the hit policy is FIRST or RULE ORDER, the ordering of the rules is significant and MUST be preserved -->
					<xsd:element name="output" type="tDTOutput" maxOccurs="unbounded"/>
					<xsd:element name="rule" type="tDecisionRule" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:attribute name="hitPolicy" type="HitPolicy" use="optional" default="UNIQUE"/>
				<xsd:attribute name="aggregation" type="BuiltinAggregator" use="optional"/>
				<xsd:attribute name="preferedOrientation" type="DecisionTableOrientation" use="optional" default="Rule-as-Row"/>
				<xsd:attribute name="isComplete" type="xsd:boolean" use="optional" default="false"/>
				<xsd:attribute name="isConsistent" type="xsd:boolean" use="optional" default="false"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="tClause">
		<xsd:attribute name="id"/>
		<xsd:attribute name="name" type="xsd:string" use="optional"/>
		<!-- NB: When the isOrdered attribute is "true", the ordering of the output entries is significant and MUST be preserved -->
		<!-- NB: irOrdered MUST be true iff the hit policy of the containing decision table is PRIORITY or OUTPUT ORDER -->
	</xsd:complexType>
	<xsd:complexType name="tDecisionRule">
		<xsd:sequence>
			<xsd:element name="inputEntry" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="tUnaryTests">
							<xsd:attribute name="inputRef" type="xsd:IDREF"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="outputEntry" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="tLiteralExpression">
							<xsd:attribute name="outputRef" type="xsd:IDREF"/>
						</xsd:extension>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID"/>
		<xsd:attribute name="isOrdered" type="xsd:boolean"/>
	</xsd:complexType>
	<xsd:element name="importedValues" type="tImportedValues" substitutionGroup="Import"/>
	<xsd:complexType name="tImportedValues">
		<xsd:complexContent>
			<xsd:extension base="tImport">
				<xsd:sequence>
					<xsd:element name="importedElement" type="xsd:string"/>
				</xsd:sequence>
				<xsd:attribute name="expressionLanguage" type="xsd:anyURI"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="artifact" type="tArtifact" abstract="true" substitutionGroup="DMNElement"/>
	<xsd:complexType name="tArtifact">
		<xsd:complexContent>
			<xsd:extension base="tDMNElement"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="textAnnotation" type="tTextAnnotation" substitutionGroup="artifact"/>
	<xsd:complexType name="tTextAnnotation">
		<xsd:complexContent>
			<xsd:extension base="tArtifact">
				<xsd:sequence>
					<xsd:element ref="text" minOccurs="0" maxOccurs="1"/>
				</xsd:sequence>
				<xsd:attribute name="textFormat" type="xsd:string" default="text/plain"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="text" type="xsd:string"/>
	<xsd:element name="association" type="tAssociation" substitutionGroup="artifact"/>
	<xsd:complexType name="tAssociation">
		<xsd:complexContent>
			<xsd:extension base="tArtifact">
				<xsd:sequence>
					<xsd:element name="sourceRef" type="tDMNElementReference"/>
					<xsd:element name="targetRef" type="tDMNElementReference"/>
				</xsd:sequence>
				<xsd:attribute name="associationDirection" type="tAssociationDirection" default="None"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="tAssociationDirection">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="None"/>
			<xsd:enumeration value="One"/>
			<xsd:enumeration value="Both"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DecisionTableOrientation">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Rule-as-Row"/>
			<xsd:enumeration value="Rule-as-Column"/>
			<xsd:enumeration value="CrossTable"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="HitPolicy">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="UNIQUE"/>
			<xsd:enumeration value="FIRST"/>
			<xsd:enumeration value="PRIORITY"/>
			<xsd:enumeration value="ANY"/>
			<xsd:enumeration value="COLLECT"/>
			<xsd:enumeration value="RULE ORDER"/>
			<xsd:enumeration value="OUTPUT ORDER"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="BuiltinAggregator">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SUM"/>
			<xsd:enumeration value="COUNT"/>
			<xsd:enumeration value="MIN"/>
			<xsd:enumeration value="MAX"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="tDTOutput">
		<xsd:complexContent>
			<xsd:extension base="tClause">
				<xsd:sequence>
					<!-- NB: When the isOrdered attribute is "true", the ordering of the output entries is significant and MUST be preserved -->
					<xsd:element name="outputDefinition" type="xsd:QName" minOccurs="0"/>
					<xsd:element name="outputValue" type="tUnaryTests" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="defaultOutputEntry" type="tLiteralExpression" minOccurs="0"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="tDTInput">
		<xsd:complexContent>
			<xsd:extension base="tClause">
				<xsd:sequence>
					<xsd:element name="inputExpression" type="tLiteralExpression"/>
					<xsd:element name="inputValue" type="tUnaryTests" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="Context" type="tContext" substitutionGroup="Expression"/>
	<xsd:complexType name="tContext">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:sequence>
					<xsd:element name="contextEntry" type="tContextEntry" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="tContextEntry">
		<xsd:sequence>
			<xsd:element ref="InformationItem" minOccurs="0" maxOccurs="1"/>
			<!-- the variable -->
			<xsd:element ref="Expression" minOccurs="1" maxOccurs="1"/>
			<!-- the value -->
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="FunctionDefinition" type="tFunctionDefinition" substitutionGroup="Expression"/>
	<xsd:complexType name="tFunctionDefinition">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:sequence>
					<xsd:element ref="InformationItem" minOccurs="0" maxOccurs="unbounded"/>
					<!-- the formal parameters -->
					<xsd:element ref="Expression" minOccurs="0" maxOccurs="1"/>
					<!-- the body -->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="Relation" type="tRelation" substitutionGroup="Expression"/>
	<xsd:complexType name="tRelation">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:sequence>
					<xsd:element name="column" type="tContextEntry" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="List" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="List" type="tList" substitutionGroup="Expression"/>
	<xsd:complexType name="tList">
		<xsd:complexContent>
			<xsd:extension base="tExpression">
				<xsd:sequence>
					<xsd:element ref="Expression" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="tUnaryTests">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:complexType name="tNamedElement">
		<xsd:complexContent>
			<xsd:extension base="tDMNElement">
				<xsd:attribute name="name" type="xsd:string" use="required"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== omg-dmn-taskforce/omg-dmn-spec/examples/dmnExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (x64) (http://www.altova.com) by Bruce Silver (private) -->
<?altova_sps dmn.sps?>
<Definitions id="def01" name="Chapter 11 example" namespace="http://brsilver.com/dmn/test01" xmlns="http://www.omg.org/spec/DMN/20130901" xmlns:tns="http://brsilver.com/dmn/test01" xmlns:feel="http://www.omg.org/spec/FEEL/20140401" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20130901 github%20branches/21.11-67%20DT%20unaryTests%20correction/dmn.xsd">
	<ItemDefinition id="tEligibility" name="tEligibility">
		<typeRef>feel:string</typeRef>
		<allowedValues>"INELIGIBLE", "ELIGIBLE"</allowedValues>
	</ItemDefinition>
	<ItemDefinition id="tBureauCallType" name="tBureauCallType">
		<typeRef>feel:string</typeRef>
		<allowedValues>"FULL", "MINI", "NONE"</allowedValues>
	</ItemDefinition>
	<ItemDefinition id="tStrategy" name="tStrategy">
		<typeRef>feel:string</typeRef>
		<allowedValues>"DECLINE", "BUREAU", "THROUGH"</allowedValues>
	</ItemDefinition>
	<ItemDefinition name="tRiskCategory" id="tRiskCategory">
		<typeRef>feel:string</typeRef>
		<allowedValues>&quot;DECLINE&quot;, &quot;HIGH&quot;, &quot;MEDIUM&quot;, &quot;LOW&quot;, &quot;VERY LOW&quot;</allowedValues>
	</ItemDefinition>
	<ItemDefinition name="tRouting" id="tRouting">
		<typeRef>feel:string</typeRef>
		<allowedValues>&quot;DECLINE&quot;, &quot;REFER&quot;, &quot;ACCEPT&quot;</allowedValues>
	</ItemDefinition>
	<ItemDefinition name="tBureauData">
		<itemComponent name="CreditScore">
			<typeRef>feel:number</typeRef>
			<allowedValues>[0..999], null</allowedValues>
		</itemComponent>
		<itemComponent name="Bankrupt">
			<typeRef>feel:boolean</typeRef>
		</itemComponent>
	</ItemDefinition>
	<ItemDefinition name="tAdjudication" id="tAdjudication">
		<typeRef>feel:string</typeRef>
		<allowedValues>&quot;DECLINE&quot;, &quot;ACCEPT&quot;</allowedValues>
	</ItemDefinition>
	<ItemDefinition name="tApplicantData" id="tApplicantData">
		<itemComponent name="Monthly">
			<itemComponent name="Income">
				<typeRef>feel:number</typeRef>
			</itemComponent>
			<itemComponent name="Expenses">
				<typeRef>feel:number</typeRef>
			</itemComponent>
			<itemComponent name="Repayments">
				<typeRef>feel:number</typeRef>
			</itemComponent>
		</itemComponent>
		<itemComponent name="Age">
			<typeRef>feel:number</typeRef>
		</itemComponent>
		<itemComponent name="ExistingCustomer">
			<typeRef>feel:boolean</typeRef>
		</itemComponent>
		<itemComponent name="MaritalStatus">
			<typeRef>feel:string</typeRef>
			<allowedValues>&quot;S&quot;,&quot;M&quot;</allowedValues>
		</itemComponent>
		<itemComponent name="EmploymentStatus">
			<typeRef>feel:string</typeRef>
			<allowedValues>&quot;EMPLOYED&quot;,&quot;SELF-EMPLOYED&quot;,&quot;STUDENT&quot;,&quot;UNEMPLOYED&quot;</allowedValues>
		</itemComponent>
	</ItemDefinition>
	<ItemDefinition name="tRequestedProduct" id="tRequestedProduct">
		<itemComponent name="ProductType">
			<typeRef>feel:string</typeRef>
			<allowedValues>&quot;STANDARD LOAN&quot;, &quot;SPECIAL LOAN&quot;</allowedValues>
		</itemComponent>
		<itemComponent name="Amount">
			<typeRef>feel:number</typeRef>
		</itemComponent>
		<itemComponent name="Rate">
			<typeRef>feel:number</typeRef>
		</itemComponent>
		<itemComponent name="Term">
			<typeRef>feel:number</typeRef>
		</itemComponent>
	</ItemDefinition>
	<Decision name="BureauCallType" id="d_BureauCallType">
		<InformationItem name="BureauCallType" id="v_BureauCallType" typeRef="tns:tBureauCallType"/>
		<informationRequirement>
			<requiredDecision href="#d_Pre-bureauRiskCategory"/>
		</informationRequirement>
		<knowledgeRequirement>
			<requiredKnowledge href="#b_BureauCallTypeTable"/>
		</knowledgeRequirement>
		<Invocation>
			<binding>
				<LiteralExpression>
					<text>Pre-bureauRiskCategory</text>
				</LiteralExpression>
				<parameter href="#p_Pre-bureauRiskCategory"/>
			</binding>
		</Invocation>
	</Decision>
	<Decision id="d_Strategy" name="Strategy">
		<description>3</description>
		<question>Is credit bureau call required?</question>
		<allowedAnswers>Yes (BUREAU) or No (DECLINE, THROUGH)</allowedAnswers>
		<InformationItem name="Strategy" id="v_Strategy" typeRef="tns:tStrategy"/>
		<informationRequirement>
			<requiredDecision href="#d_BureauCallType"/>
		</informationRequirement>
		<informationRequirement>
			<requiredDecision href="#d_Eligibility"/>
		</informationRequirement>
		<DecisionTable hitPolicy="UNIQUE" isComplete="true" isConsistent="true" preferedOrientation="Rule-as-Row">
			<input name="Eligibility" id="ix_Strategy.Eligibility">
				<inputExpression>
					<text>Eligibility</text>
				</inputExpression>
				<inputValues>"ELIGIBLE", "INELIGIBLE"</inputValues>
			</input>
			<input name="BureauCall" id="ix_Strategy.BureauCall">
				<inputExpression>
					<text>BureauCallType</text>
				</inputExpression>
				<inputValues>"FULL", "MINI", "NONE"</inputValues>
			</input>
			<output name="Strategy"/>
			<rule>
				<inputEntry inputRef="ix_Strategy.Eligibility">"INELIGIBLE"</inputEntry>
				<inputEntry inputRef="ix_Strategy.BureauCall">-</inputEntry>
				<outputEntry>
					<text>"DECLINE"</text>
				</outputEntry>
			</rule>
			<rule>
				<inputEntry inputRef="ix_Strategy.Eligibility">"ELIGIBLE"</inputEntry>
				<inputEntry inputRef="ix_Strategy.BureauCall">"FULL","MINI"</inputEntry>
				<outputEntry>
					<text>"BUREAU"</text>
				</outputEntry>
			</rule>
			<rule>
				<inputEntry inputRef="ix_Strategy.Eligibility">"ELIGIBLE"</inputEntry>
				<inputEntry inputRef="ix_Strategy.BureauCall">"NONE"</inputEntry>
				<outputEntry>
					<text>"THROUGH"</text>
				</outputEntry>
			</rule>
		</DecisionTable>
	</Decision>
	<Decision id="d_Eligibility" name="Eligibility">
		<InformationItem name="Eligibility" id="v_Eligibility" typeRef="tns:tEligibility"/>
		<informationRequirement>
			<requiredDecision href="#d_Pre-bureauRiskCategory"/>
		</informationRequirement>
		<informationRequirement>
			<requiredInput href="#i_ApplicantData"/>
		</informationRequirement>
		<informationRequirement>
			<requiredDecision href="#d_Pre-bureauAffordability"/>
		</informationRequirement>
		<knowledgeRequirement>
			<requiredKnowledge href="#b_EligibilityRules"/>
		</knowledgeRequirement>
		<Invocation>
			<binding>
				<LiteralExpression>
					<text>Pre-bureau Affordability</text>
				</LiteralExpression>
				<parameter href="#p_EligibilityRules.Pre-bureauAffordability"/>
			</binding>
			<binding>
				<LiteralExpression>
					<text>Pre-bureau Risk Category</text>
				</LiteralExpression>
				<parameter href="#p_EligibilityRules.Pre-bureauRiskCategory"/>
			</binding>
			<binding>
				<LiteralExpression>
					<text>Applicant Data.Age</text>
				</LiteralExpression>
				<parameter href="#p_EligibilityRules.Age"/>
			</binding>
		</Invocation>
	</Decision>
	<Decision name="Pre-bureauRiskCategory" id="d_Pre-bureauRiskCategory">
		<InformationItem name="Pre-bureauRiskCategory" typeRef="tns:tRiskCategory" id="v_Pre-bureauRiskCategory"/>
		<informationRequirement>
			<requiredDecision href="#d_ApplicationRiskScore"/>
		</informationRequirement>
		<informationRequirement>
			<requiredInput href="#i_ApplicantData"/>
		</informationRequirement>
		<knowledgeRequirement>
			<requiredKnowledge href="#b_Pre-bureauRiskCategoryTable"/>
		</knowledgeRequirement>
		<Invocation>
			<binding>
				<LiteralExpression>
					<text>ApplicantData.ExistingCustomer</text>
				</LiteralExpression>
				<parameter href="#p_Pre-bureauRiskCategoryTable.ExistingCustomer"/>
			</binding>
			<binding>
				<LiteralExpression>
					<text>ApplicationRiskScore</text>
				</LiteralExpression>
				<parameter href="#p_Pre-bureauRiskCategoryTable.ApplicationRiskScore"/>
			</binding>
		</Invocation>
	</Decision>
	<Decision name="Post-bureauRiskCategory" id="d_Post-bureauRiskCategory">
		<InformationItem name="Post-bureauRiskCategory" id="v_Post-bureauRiskCategory" typeRef="tns:tRiskCategory"/>
		<informationRequirement>
			<requiredInput href="#i_ApplicantData"/>
		</informationRequirement>
		<informationRequirement>
			<requiredDecision href="#d_ApplicationRiskScore"/>
		</informationRequirement>
		<informationRequirement>
			<requiredInput href="#i_BureauData"/>
		</informationRequirement>
		<knowledgeRequirement>
			<requiredKnowledge href="#b_Post-bureauRiskCategoryTable"/>
		</knowledgeRequirement>
		<Invocation>
			<binding>
				<LiteralExpression>
					<text>ApplicantData.ExistingCustomer</text>
				</LiteralExpression>
				<parameter href="#p_Post-bureauRiskCategoryTable.ExistingCustomer"/>
			</binding>
			<binding>
				<LiteralExpression>
					<text>BureauData.CreditScore</text>
				</LiteralExpression>
				<parameter href="#p_Post-bureauRiskCategoryTable.CreditScore"/>
			</binding>
			<binding>
				<LiteralExpression>
					<text>ApplicationRiskScore</text>
				</LiteralExpression>
				<parameter href="#p_Post-bureauRiskCategoryTable.ApplicationRiskScore"/>
			</binding>
		</Invocation>
	</Decision>
	<Decision name="ApplicationRiskScore" id="d_ApplicationRiskScore">
		<InformationItem name="ApplicationRiskScore" typeRef="feel:number" id="v_ApplicationRiskScore"/>
		<informationRequirement>
			<requiredInput href="#i_ApplicantData"/>
		</informationRequirement>
		<knowledgeRequirement>
			<requiredKnowledge href="#b_ApplicationRiskScoreModel"/>
		</knowledgeRequirement>
		<Invocation>
			<binding>
				<LiteralExpression>
					<text>ApplicantData.Age</text>
				</LiteralExpression>
				<parameter href="#p_ApplicationRiskScoreModel.Age"/>
			</binding>
			<binding>
				<LiteralExpression>
					<text>ApplicantData.MaritalStatus</text>
				</LiteralExpression>
